config/routes.rb
Rails.application.routes.draw do
        resources :suggestions
        root "suggestions#index"

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
        # Prevent CSRF attacks by raising an exception.
        # For APIs, you may want to use :null_session instead.
        # protect_from_forgery with: :exception
        skip_before_filter :verify_authenticity_token
end

app/controllers/suggestions_controller.rb
# -*- coding: utf-8 -*-
class SuggestionsController < ApplicationController
        before_action :set_suggestion, only: [:show, :edit, :update, :destroy]

        # GET /suggestions
        # GET /suggestions.json
        def index
                @suggestions = Suggestion.all
        end

        # GET /suggestions/1
        # GET /suggestions/1.json
        def show
        end

        # GET /suggestions/new
        def new
                @suggestion = Suggestion.new
        end

        # GET /suggestions/1/edit
        def edit
        end

        # POST /suggestions
        # POST /suggestions.json
        def create
                @suggestion = Suggestion.new(suggestion_params)

                respond_to do |format|
                        if @suggestion.save
                                format.html { redirect_to @suggestion, notice: 'Suggestion was successfully created.' }
                                format.json { render :show, status: :created, location: @suggestion }
                        else
                                format.html { render :new }
                                format.json { render json: @suggestion.errors, status: :unprocessable_entity }
                        end
                end
        end

        # PATCH/PUT /suggestions/1
        # PATCH/PUT /suggestions/1.json
        def update
                respond_to do |format|
                        if @suggestion.update(suggestion_params)
                                format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
                                format.json { render :show, status: :ok, location: @suggestion }
                        else
                                format.html { render :edit }
                                format.json { render json: @suggestion.errors, status: :unprocessable_entity }
                        end
                end
        end

        # DELETE /suggestions/1
        # DELETE /suggestions/1.json
        def destroy
                @suggestion.destroy
                respond_to do |format|
                        format.html { redirect_to suggestions_url, notice: '删除成功。' }
                        format.json { head :no_content }
                end
        end

        private
        # Use callbacks to share common setup or constraints between actions.
        def set_suggestion
                @suggestion = Suggestion.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def suggestion_params
                params.require(:suggestion).permit(:content)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">昆明医保信息服务平台</a>
        </div>
        <div style="display:table" class="pull-right">
          <a href="" class="navbar-brand">
            <i class="material-icons">android</i>
          </a>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/suggestions">意见与建议</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Editing Suggestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<% if notice.present? %>
<p class="alert alert-info" id="notice"><%= notice %></p>
<% end %>

<h1 class="page-header">意见与建议</h1>

<table class="table">
  <thead>
    <tr>
      <th>建议内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suggestions.each do |suggestion| %>
      <tr>
        <td><%= suggestion.content %></td>
        <td><%= link_to '查看', suggestion %></td>
        <td><%= link_to '删除', suggestion, method: :delete, data: { confirm: '确定要删除该建议吗?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/suggestions/new.html.erb
<h1>New Suggestion</h1>

<%= render 'form' %>

<%= link_to 'Back', suggestions_path %>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>建议内容:</strong>
  <%= @suggestion.content %>
</p>

<%= link_to '返回', suggestions_path, class: "btn btn-default" %>